touch Readme.md && git init && git add . && git commit -m  "feat: initial commit" && echo >> Readme.md "`modulo` \n## Módulo: Nombre del modulo\n\n### OBJETIVO \n - Agrega lo que van a aprender en el modulo
 \n\n### ORGANIZACIÓN DE MÓDULO \n - [Sesión 1](): \n - [Sesión 2](): \n - [Sesión 3](): \n - [Sesión 4](): \n - [Sesión 5](): \n - [Sesión 6](): \n - [Sesión 7](): \n - [Sesión 8]():
"&& git add . && git commit -m "docs: Actualizando readme" && for i in {1..8}; do mkdir Sesion-0$i && cd Sesion-0$i && 
for a in {1..3}; do mkdir Reto-0$a && cd Reto-0$a && touch Readme.md && git add . && git commit -m "feat: Agregando readme a Reto-0$a" && echo >> Readme.md " agrega el programa que se desarrollara con backticks> [agrega la sesion con backticks]  \n## Titulo del Ejemplo \n\n### OBJETIVO \n - Lo que esperamos que el alumno aprenda \n\n#### REQUISITOS \n1. Lo necesario para desarrollar el ejemplo o el Reto \n\n#### DESARROLLO
"  && git add . && git commit -m "feat: Actualizando readme a Reto-0$a" && cd .. && mkdir Ejemplo-0$a && cd Ejemplo-0$a && touch Readme.md && git add . && git commit -m "feat: Agregando readme a Ejemplo-0$i" && echo >> Readme.md " agrega el programa que se desarrollara con backticks> [agrega la sesion con backticks]  \n## Titulo del Ejemplo \n\n### OBJETIVO \n - Lo que esperamos que el alumno aprenda \n\n#### REQUISITOS \n1. Lo necesario para desarrollar el ejemplo o el Reto \n\n#### DESARROLLO
" && git add . && git commit -m "docs: Actualizando readme a Ejemplo-0$a" && cd ..; done
mkdir Postwork && cd Postwork && touch Readme.md && git add . && git commit -m "feat: Agregando readme a Postwork de la Sesion $i" && echo >> Readme.md " agrega el programa que se desarrollara con backticks> [agrega la sesion con backticks]  \n## Titulo del Ejemplo \n\n### OBJETIVO \n - Lo que esperamos que el alumno aprenda \n\n#### REQUISITOS \n1. Lo necesario para desarrollar el ejemplo o el Reto \n\n#### DESARROLLO
" && git add . && git commit -m "docs: Actualizando readme a Postwork de la Sesion $i" && cd .. && touch Readme.md && git add . && git commit -m "feat: Agregando readme a la Sesion $i" && echo >> Readme.md " agrega el programa que se desarrollara con backticks> [agrega la sesion con backticks]  \n## Titulo de la Sesion \n\n### OBJETIVOS \n - Lo que esperamos que el alumno aprenda al finalizar la sesion \n\n#### ORGANIZACION DE LA CLASE \n- Tema que veran en el ejemplo\n\t- [Ejemplo 01](Ejemplo-01)\n\t- [Reto 01](Reto-01)
" && git add . && git commit -m "docs: Actualizando readme" && 
cd .. ; done

